### ISSUE TITLE
TypeError on manipulating queries

### ISSUE THREAD

**Issue by pocketoffice** [sbuberl/fSQL#13]
hey

thanks for this great library. 
i'e got it up and running and was able to create tables. but as i try to insert into a table i#ve got an error
`Argument 1 passed to FSQL\Database\TableCursor::__construct() must be of the type array, null given`

thats what my create and insert queries look like

`$fsql->query("CREATE TABLE usergroup (
   id INT NOT NULL AUTO_INCREMENT,
   name VARCHAR(255),
   desc VARCHAR(500),
   active INT,
   created DATE,
   PRIMARY KEY(id)
)") or die($fsql->error());`

`$fsql->query( "INSERT INTO usergroup (name, desc, active, created) VALUES ('admin', 'Users with administrative Rights', 1, '2017-01-01')" )
or die($fsql->error());`

would be awesome if you could point me to what i'm doing wrong. 
i would really like to use the library and would contribute documentation in contrary. 

thanks in advance
daniel

**Comment by sbuberl** [comment]
Hello,

Thanks for the report.  What version were you using?  Or were you using cloned version of this repo?

Steve

**Comment by pocketoffice** [comment]
hi

yes, i use a cloned version of this repo.
meanwhile i think i've found whats causing the error, at least changing CachedTable.php Line 229 from
`$entries = null;`
to
`$entries = array();`
let me insert without errors.

**Comment by sbuberl** [comment]
Good catch.  Possibly some legacy code I didn't notice.  So $entries was assigned to empty array if table was not empty, but for empty tables, it was using that NULL.

Unfortunately my unit tests are only at like 50% code coverage.  Mostly CREATE and SELECT tests. 
 Otherwise, that definitely would been caught by an INSERT test.  If I have some free time this weekend, hopefully I can work on some tests.

**Comment by sbuberl** [comment]
I apparently I had a test for this in CachedTableTest for the class level test.  But I was checking whether the return entries were empty (as in the php function empty).  So both null and empty arrays were passing the test.   I push a fix for the test as well so only empty arrays pass.

Hopefully I'll still work on adding new tests this weekend.
